window.VSEBINA = {
  "imeBenda": "ASTIŠENAMORJU",
  "logotip": "",
  "naslovStrani": "ASTIŠENAMORJU — avtorski akustični pop/rock",
  "metaOpis": "ASTIŠENAMORJU — avtorski akustični pop in rock z dotikom countryja in dobrimi besedili.",
  "barvaOzadja": "#400000",
  "barvaPapirja": "#f0eadf",
  "barvaPoudarka": "#d56f3e",
  "menu1": "Zgodba",
  "menu1Link": "#zgodba",
  "menu2": "Glasba",
  "menu2Link": "#glasba",
  "menu3": "V živo",
  "menu3Link": "#v-zivo",
  "menu4": "Galerija",
  "menu4Link": "#galerija",
  "menu5": "Kontakt",
  "menu5Link": "#kontakt",
  "eyebrow": "Avtorski akustični pop / rock in še kaj drugega",
  "naslov": "Še vedno",
  "poudarek": "na morju?",
  "uvodniOpis": "Dve akustični kitari, bas, bobni in dva glasova. Pesmi, ki najprej nekaj povedo — potem pa ostanejo v ušesu.",
  "video": "assets/naslovni-video-web.mp4",
  "videoPoster": "assets/skupina-rdeca.jpg",
  "videoPozicija": "center center",
  "heroGumb1": "Poslušaj nas",
  "heroGumb1Link": "#glasba",
  "heroGumb2": "Povabi nas",
  "heroGumb2Link": "#kontakt",
  "scrollTekst": "Pomakni se navzdol ↓",
  "storyIndex": "01 / Kdo smo",
  "storyTitle": "Ime je vprašanje. Glasba je odgovor.",
  "zgodba1": "ASTIŠENAMORJU je besedna igra, ki se je prijela kot dobro vprašanje med prijatelji: »A si ti še vedno na morju?«",
  "zgodba2": "Igramo izključno avtorske skladbe — akustični pop in rock z nekaj country prahu na čevljih. V ospredju so zgodbe, besede in ljudje, ki radi igrajo skupaj.",
  "storySlika": "assets/skupina-rdeca.jpg",
  "storySlikaAlt": "Člani skupine ASTIŠENAMORJU po nastopu",
  "storySlikaPozicija": "center center",
  "storySlikaVelikost": "100",
  "storySlikaNacin": "cover",
  "zasedba1": "2× akustična kitara",
  "zasedba2": "bas",
  "zasedba3": "bobni",
  "zasedba4": "2× vokal",
  "musicIndex": "02 / Glasba",
  "musicTitle": "Pesmi z besedami.",
  "musicDescription": "Avtorske skladbe, ki živijo med popom, rockom in countryjem — vedno s poudarkom na zgodbi.",
  "skladba1": "Eufemija",
  "skladba1Opis": "Avtorska skladba · v živo",
  "skladba1Link": "https://1drv.ms/u/c/89017a45320dda76/IQAqvCutMyOiQboQ-tLZ2b0lAcKBhNndGSb9zPlqz3VIYy0?e=BZCOeH",
  "skladba2": "Magija",
  "skladba2Opis": "Avtorska skladba · v živo",
  "skladba2Link": "",
  "musicNote": "Posnetke in povezave dodamo, ko izberemo uradne različice.",
  "liveIndex": "03 / V živo",
  "liveTitle": "Najbolje zvenimo v istem prostoru.",
  "liveDescription": "Klubi, manjši odri, festivali in večeri, kjer imajo pesmi dovolj prostora.",
  "liveLinkText": "Dogovori se za nastop →",
  "liveLinkUrl": "#kontakt",
  "liveSlika": "assets/nastop-muzej.jpg",
  "liveSlikaAlt": "ASTIŠENAMORJU med koncertom",
  "liveSlikaPozicija": "center center",
  "liveSlikaVelikost": "100",
  "liveSlikaNacin": "cover",
  "liveCaption": "Utrinek z nastopa · koncertni arhiv",
  "galleryIndex": "04 / Galerija",
  "galleryTitle": "Med odrom in zakulisjem.",
  "galleryDescription": "Nekaj utrinkov z vaj, koncertov in trenutkov med pesmimi.",
  "gallery1": "assets/nastop-intimno.jpg",
  "gallery1Alt": "Intimni koncert skupine ASTIŠENAMORJU",
  "gallery1Pozicija": "center center",
  "gallery2": "assets/oder-transparent.jpg",
  "gallery2Alt": "Oder s transparentom ASTIŠENAMORJU",
  "gallery2Pozicija": "center center",
  "gallery3": "assets/gallery3.jpg",
  "gallery3Alt": "Člana skupine v zakulisju",
  "gallery3Pozicija": "50% 50%",
  "galerija": [
    {
      "slika": "assets/nastop-intimno.jpg",
      "opis": "Intimni koncert skupine ASTIŠENAMORJU",
      "pozicija": "center center",
      "velikost": "100",
      "nacin": "cover"
    },
    {
      "slika": "assets/oder-transparent.jpg",
      "opis": "Oder s transparentom ASTIŠENAMORJU",
      "pozicija": "center center",
      "velikost": "100",
      "nacin": "cover"
    },
    {
      "slika": "assets/gallery3.jpg",
      "opis": "Člana skupine v zakulisju",
      "pozicija": "50% 20%",
      "velikost": "100",
      "nacin": "contain"
    },
    {
      "slika": "assets/gallery-20260716-103121146.jpg",
      "opis": "Razpoloženje na vajah",
      "pozicija": "center top",
      "velikost": "100",
      "nacin": "contain"
    },
    {
      "slika": "assets/gallery-20260716-105630218.jpeg",
      "opis": "Koncert na fužinskem gradu",
      "pozicija": "center center",
      "velikost": "50",
      "nacin": "contain"
    },
    {
      "slika": "assets/gallery-20260716-121526726.jpg",
      "opis": "",
      "pozicija": "center center",
      "velikost": "100",
      "nacin": "cover"
    }
  ],
  "contactIndex": "05 / Kontakt",
  "contactTitle": "Se vidimo",
  "contactHighlight": "na kopnem?",
  "contactDescription": "Za koncerte, sodelovanja ali samo dobro vprašanje.",
  "kontakt": "kontakt@astisenamorju.si",
  "facebookText": "Facebook",
  "facebookUrl": "",
  "instagramText": "Instagram",
  "instagramUrl": "",
  "youtubeText": "YouTube",
  "youtubeUrl": "",
  "footerLeft": "© 2026 ASTIŠENAMORJU",
  "footerRight": "Avtorska glasba · Slovenija",
  "menu6": "",
  "menu6Link": "",
  "menu7": "",
  "menu7Link": "",
  "menu8": "",
  "menu8Link": "",
  "menu9": "",
  "menu9Link": ""
};
