window.VSEBINA = {
  "imeBenda": "",
  "headerMode": "grafika",
  "imeGrafika": "assets/imegrafika.png",
  "imeGrafikaVelikost": "50",
  "imeGrafikaOdmikX": "0",
  "imeGrafikaOdmikY": "0",
  "logotip": "assets/logotip.png",
  "naslovStrani": "ASTIŠENAMORJU — avtorski akustični pop/rock",
  "metaOpis": "ASTIŠENAMORJU — avtorski akustični pop in rock z dotikom countryja in dobrimi besedili.",
  "barvaOzadja": "#400000",
  "barvaPapirja": "#f0eadf",
  "barvaPoudarka": "#d56f3e",
  "glavaBarvaOzadja": "prosojno",
  "glavaBarvaBesedila": "#FFE9D2",
  "menu1": "Zgodba",
  "menu1Link": "#zgodba",
  "menu2": "Glasba",
  "menu2Link": "#glasba",
  "menu3": "V živo",
  "menu3Link": "#v-zivo",
  "menu4": "Galerija",
  "menu4Link": "#galerija",
  "menu5": "Video",
  "menu5Link": "#video",
  "eyebrow": "Avtorski akustični pop / rock in še kaj drugega",
  "naslov": "Še vedno",
  "poudarek": "na morju?",
  "uvodniOpis": "Pesmi, ki najprej nekaj povedo — potem pa ostanejo v ušesu.",
  "video": "assets/naslovni-video-web.mp4",
  "videoPoster": "assets/skupina-rdeca.jpg",
  "videoPozicija": "center center",
  "heroGumb1": "Poslušaj nas",
  "heroGumb1Link": "#glasba",
  "heroGumb2": "Povabi nas",
  "heroGumb2Link": "#kontakt",
  "scrollTekst": "Pomakni se navzdol ↓",
  "storyIndex": "01 / Kdo smo",
  "storyTitle": "Ime je vprašanje. Glasba je odgovor.",
  "zgodba1": "Člani benda smo: Šani Kolbezen, vokal, kitara, Silvester Bukovec, vokal, kitara, Tomaž Polak, vokal, bas ter Matej Palka, vokal, bobni.",
  "zgodba2": "Igramo izključno avtorske skladbe — akustični pop in rock z nekaj country prahu na čevljih. V ospredju so zgodbe, besede in ljudje, ki radi igrajo skupaj.",
  "storySlika": "assets/skupina-rdeca.jpg",
  "storySlikaAlt": "Člani skupine ASTIŠENAMORJU po nastopu",
  "storySlikaPozicija": "center center",
  "storySlikaVelikost": "100",
  "storySlikaNacin": "cover",
  "zasedba1": "akustična kitara",
  "zasedba2": "bas",
  "zasedba3": "bobni",
  "zasedba4": "vokal",
  "musicIndex": "02 / Glasba",
  "musicTitle": "Pesmi z besedami.",
  "musicDescription": "Avtorske skladbe, ki živijo med popom, rockom in countryjem — vedno s poudarkom na zgodbi.",
  "pesmi": [],
  "musicNote": "Posnetke in povezave dodamo, ko izberemo uradne različice.",
  "liveIndex": "03 / V živo",
  "liveTitle": "Najbolje zvenimo v istem prostoru.",
  "liveDescription": "Klubi, manjši odri, festivali in večeri, kjer imajo pesmi dovolj prostora.",
  "liveLinkText": "Dogovori se za nastop →",
  "liveLinkUrl": "#kontakt",
  "liveSlika": "assets/nastop-muzej.jpg",
  "liveSlikaAlt": "",
  "liveSlikaPozicija": "center center",
  "liveSlikaVelikost": "100",
  "liveSlikaNacin": "cover",
  "liveCaption": "",
  "galleryIndex": "04 / Galerija",
  "galleryTitle": "Med odrom in zakulisjem.",
  "galleryDescription": "Nekaj utrinkov z vaj, koncertov in trenutkov med pesmimi.",
  "gallery1": "assets/nastop-intimno.jpg",
  "gallery1Alt": "Intimni koncert skupine ASTIŠENAMORJU",
  "gallery1Pozicija": "center center",
  "gallery2": "assets/oder-transparent.jpg",
  "gallery2Alt": "Oder s transparentom ASTIŠENAMORJU",
  "gallery2Pozicija": "center center",
  "gallery3": "assets/gallery3.jpg",
  "gallery3Alt": "Člana skupine v zakulisju",
  "gallery3Pozicija": "50% 50%",
  "galerija": [
    {
      "slika": "assets/gallery-20261006-134201005.jpg",
      "opis": "",
      "pozicija": "center center",
      "velikost": "100",
      "nacin": "cover"
    },
    {
      "slika": "assets/gallery-20261006-134206898.jpg",
      "opis": "",
      "pozicija": "center center",
      "velikost": "100",
      "nacin": "cover"
    },
    {
      "slika": "assets/gallery-20261006-134827153.jpg",
      "opis": "",
      "pozicija": "center center",
      "velikost": "100",
      "nacin": "cover"
    }
  ],
  "contactIndex": "06 / Kontakt",
  "contactTitle": "Se vidimo",
  "contactHighlight": "na kopnem?",
  "contactDescription": "Za koncerte, sodelovanja ali samo dobro vprašanje.",
  "kontakt": "kontakt@astisenamorju.si",
  "facebookText": "Facebook",
  "facebookUrl": "",
  "instagramText": "Instagram",
  "instagramUrl": "",
  "youtubeText": "YouTube",
  "youtubeUrl": "",
  "footerLeft": "© 2026 ASTIŠENAMORJU",
  "footerRight": "Avtorska glasba · Slovenija",
  "videoIndex": "05 / Video",
  "videoTitle": "Posnetki in pogledi v ozadje.",
  "videoDescription": "Izbrani posnetki — ko glasba ujame še sliko.",
  "videoteka": [
    {
      "video": "https://youtu.be/z81aeNS1wKs",
      "naslov": "Posnetki koncerta v Okrepčevalnici Kolišče",
      "aktiven": "da"
    }
  ],
  "menu6": "Kontakt",
  "menu6Link": "#kontakt",
  "menu7": "",
  "menu7Link": "",
  "menu8": "",
  "menu8Link": "",
  "menu9": "",
  "menu9Link": ""
};
