<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>AstisenamorjuUrejevalnik</RootNamespace>
    <StartupObject>AstisenamorjuUrejevalnik.Program</StartupObject>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <ApplicationIcon />
  </PropertyGroup>
  <Target Name="CopyWithSourceToPublish" AfterTargets="Publish">
    <Copy SourceFiles="AstisenamorjuUrejevalnik.vbproj;MainForm.vb;Program.vb;SiteContent.vb;NuGet.Config;README.txt" DestinationFolder="$(PublishDir)" />
  </Target>
</Project>
